### ISSUE TITLE
Code Patch For Manufacturer Name

### ISSUE THREAD

**Issue by GreyHak** [0xjc/SatisfactoryLP#1]
Thank you for the great tool @0xjc !  I have a one-line change which would allow the output spreadsheet to indicate what machine is used to make items instead of just saying "manufacturer".

Change line 616 from:
     type_="manufacturer",
to
     type_=recipe["manufacturer"][6:-2],

**Comment by 0xjc** [comment]
Glad you're finding it useful. Resolved by 7780033c58521bedb3b7b59ac4ea244ec6da4f10.

**Comment by GreyHak** [comment]
Thank you @0xjc :-)
